# Build a deb artifact on commit

name: CI

on: [push, pull_request]

jobs:
  shellcheck:
    runs-on: arch-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run shellcheck
      uses: ludeeus/action-shellcheck@master

